theme: jekyll-theme-hacker
name: explosions
title: CAnderson's page of disassembly and tinkering  
description: Knowing is not enough; we must apply. Willing is not enough; we must do.
show_downloads: false
show_repo: false
