theme: jekyll-theme-hacker
name: explosions
title: sinbeard's Trove of Disassembly and Tinkering  
description: Knowing is not enough; we must apply. Willing is not enough; we must do.
show_downloads: false
show_repo: false
